/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-fruteriacastillo-65ZiSWMi11eCJqSpEsnJ4P-ALXZ-t6SJ",
  "version": "2020-11-20"
}

export default ebconfig;